### ISSUE TITLE
REST_API_v2/Incidents/list_incidents.py error line 44

### ISSUE THREAD

**Issue by kaido89** [PagerDuty/API_Python_Examples#18]
There is an issue in the line 
65:         'sort_by[]': SORT_BY,
it should be
65:         'sort_by': SORT_BY,
tested with
44: SORT_BY = ['urgency:ASC']
65:          'sort_by': SORT_BY,

**Comment by Deconstrained** [comment]
@kaido89 Thanks for pointing this out! That is indeed not a list-type parameter but rather a single-valued one with the sort attributes comma-separated (in order to least/greatest precedence). I have applied a fix for this in commit 990554f.
