### ISSUE TITLE
Create incident example is a GetIncident example

### ISSUE THREAD

**Issue by kodieGlosser** [PagerDuty/API_Python_Examples#3]
https://github.com/PagerDuty/API_Python_Examples/blob/master/REST_API_v2/Incidents/create_incident_note.py

Is in example for getting an incident.

**Comment by lfepp** [comment]
Thanks for point this out! Resolved this issue with [this PR](https://github.com/PagerDuty/API_Python_Examples/pull/4). Let me know if there are any follow-up questions.
